Support automatically taking screenshots on exit

diff --git a/.github/workflows/elixir.yml b/.github/workflows/elixir.yml
--- a/.github/workflows/elixir.yml
+++ b/.github/workflows/elixir.yml
@@ -62,6 +62,12 @@ jobs:
         run: npm exec --prefix priv/static/assets playwright install chromium --with-deps --only-shell
       - name: Run tests
         run: "mix test --warnings-as-errors --max-cases 1 || if [[ $? = 2 ]]; then PLAYWRIGHT_TRACE=true mix test --max-cases 1 --failed; else false; fi"
+      - name: Fail if screenshot on exit failed
+        run: |
+          if [[ ! -f screenshots_for_verification/test_screenshot_3_saves_screenshot_on_test_exit* ]]; then
+            echo "Screenshot on exit feature failed"
+            exit 1
+          fi
       - name: Upload failure traces
         uses: actions/upload-artifact@v4
         if: failure()
