Move @tag tests to CaseTest, add @trace test

diff --git a/.github/workflows/elixir.yml b/.github/workflows/elixir.yml
--- a/.github/workflows/elixir.yml
+++ b/.github/workflows/elixir.yml
@@ -64,8 +64,14 @@ jobs:
         run: "mix test --warnings-as-errors --max-cases 1 || if [[ $? = 2 ]]; then PLAYWRIGHT_TRACE=true mix test --max-cases 1 --failed; else false; fi"
       - name: Fail if screenshot on exit failed
         run: |
-          if ! ls screenshots/PhoenixTest.PlaywrightTest.test_screenshot_3_saves_screenshot_on_test_exit* >/dev/null 2>&1; then
+          if ! ls screenshots/PhoenixTest.CaseTest.test__tag__screenshot_saves_screenshot_on_test_exit* >/dev/null 2>&1; then
             echo "Screenshot on exit feature failed"
+            exit 1
+          fi
+      - name: Fail if trace on exit failed
+        run: |
+          if ! ls traces/PhoenixTest.CaseTest.test__tag__trace_saves_trace_on_test_exit* >/dev/null 2>&1; then
+            echo "Trace on exit feature failed"
             exit 1
           fi
       - name: Upload failure traces
